#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, '..');
const DATA = join(ROOT, 'data');
const DOCS = join(ROOT, 'docs');

function readJson(p) { return JSON.parse(readFileSync(p, 'utf8')); }
function ensureDir(p) { mkdirSync(p, { recursive: true }); }
function write(p, s) { ensureDir(dirname(p)); writeFileSync(p, s, 'utf8'); }

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

// Warm "cooking site" palette (terracotta + honey) for light and dark modes.
const EXTRA_CSS = `/* cookwhat — warm kitchen palette (generated by build-docs.js) */
:root > * {
  --md-primary-fg-color:        #b4451f; /* terracotta / paprika */
  --md-primary-fg-color--light: #c8623c;
  --md-primary-fg-color--dark:  #8f3617;
  --md-accent-fg-color:         #d98324; /* honey / amber */
}

/* Light mode: warm cream paper instead of stark white */
[data-md-color-scheme="default"] {
  --md-default-bg-color:    #fbf6ee;
  --md-code-bg-color:       #f3ebdf;
  --md-typeset-a-color:     #b4451f;
}

/* Dark mode: warm charcoal, lifted terracotta/honey for contrast */
[data-md-color-scheme="slate"] {
  --md-primary-fg-color: #d2693f;
  --md-accent-fg-color:  #e6a23c;
  --md-default-bg-color: #20191590; /* warm-tinted */
  --md-typeset-a-color:  #e8956a;
}
[data-md-color-scheme="slate"] {
  --md-hue: 25; /* shift Material's slate toward warm brown */
}

/* Editorial headings */
.md-typeset h1, .md-typeset h2, .md-typeset h3 { font-weight: 600; }

/* Tighter, friendlier dish tables */
.md-typeset table:not([class]) { font-size: .78rem; }
`;

function fmtDate(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

function localISO(d) {
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const da = String(d.getDate()).padStart(2, '0');
  return `${d.getFullYear()}-${m}-${da}`;
}

// Sunday of the week containing `d`. Weeks start on Sunday.
function sundayOf(d) {
  const x = new Date(d);
  x.setDate(x.getDate() - x.getDay());
  return localISO(x);
}

function addDays(iso, n) {
  const d = new Date(iso + 'T00:00:00');
  d.setDate(d.getDate() + n);
  return localISO(d);
}

function stars(n) {
  return '★'.repeat(n) + '☆'.repeat(5 - n);
}

// Decode HTML entities that arrive in JSON-LD recipe names (e.g. &#8217; &amp;).
function decodeEntities(s) {
  if (!s) return s;
  return String(s)
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)))
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');
}

// ---- Ratings helpers (shared by menu & recipe pages) -----------------------

function avgRating(ratings) {
  const rs = ratings.filter(r => typeof r.rating === 'number');
  if (!rs.length) return null;
  return rs.reduce((a, b) => a + b.rating, 0) / rs.length;
}

// One-line summary, e.g. "★★★★☆ 4.0/5 · 2 reviews · would cook again ✓"
function ratingSummaryLine(ratings) {
  const avg = avgRating(ratings);
  const parts = [];
  if (avg != null) parts.push(`${stars(Math.round(avg))} **${avg.toFixed(1)}/5**`);
  parts.push(`${ratings.length} review${ratings.length > 1 ? 's' : ''}`);
  if (ratings.some(r => r.redo)) parts.push('would cook again ✓');
  return parts.join(' · ');
}

// Full per-review block, newest first.
function renderReviews(ratings, heading = '## My Reviews & Ratings') {
  const out = [heading + '\n'];
  const sorted = [...ratings].sort((a, b) => b.date.localeCompare(a.date));
  for (const r of sorted) {
    const redoFlag = r.redo ? ' · would cook again ✓' : '';
    out.push(`${stars(r.rating)} **${r.rating}/5** · ${fmtDate(r.date)}${redoFlag}`);
    if (r.notes) out.push(`\n> *${r.notes}*`);
    out.push('');
  }
  return out.join('\n');
}

function ratingsFor(ratingsByTitle, ...titles) {
  for (const t of titles) {
    const key = (t || '').toLowerCase().trim();
    if (key && ratingsByTitle[key]?.length) return ratingsByTitle[key];
  }
  return null;
}

// ---- Day / dish helpers ----------------------------------------------------

const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const DAY_FULL = {
  Sun: 'Sunday', Mon: 'Monday', Tue: 'Tuesday', Wed: 'Wednesday',
  Thu: 'Thursday', Fri: 'Friday', Sat: 'Saturday',
};

function titleCase(s) {
  return String(s).replace(/(^|[-\s])\w/g, m => m.toUpperCase());
}

function isSide(dish) {
  return (dish.role || 'main') === 'side';
}

function dayDate(week, day) {
  const i = DAYS.indexOf(day);
  return i >= 0 ? addDays(week, i) : week;
}

// Group a menu's dishes by day, Sunday-first.
function dishesByDay(menu) {
  const map = new Map();
  for (const m of menu.meals) {
    if (!map.has(m.day)) map.set(m.day, []);
    map.get(m.day).push(m);
  }
  return [...map.entries()].sort((a, b) => DAYS.indexOf(a[0]) - DAYS.indexOf(b[0]));
}

// Recipe open-links for a dish. `rel` is the path prefix back to docs root
// ('' from index.md, '../' from menus/ or days/). Gives a same-tab button, a
// new-tab button, and the external source — so you can fan out 3 recipes.
function recipeLinks(dish, recipesByMealId, rel) {
  const links = [];
  if (recipesByMealId[dish.id]) {
    const p = `${rel}recipes/${dish.id}.md`;
    links.push(`[View recipe](${p})`);
    links.push(`[↗ new tab](${p}){ target="_blank" }`);
  }
  if (dish.sourceUrl) {
    links.push(`[source ↗](${dish.sourceUrl}){ target="_blank" rel="noopener" }`);
  }
  return links.join(' · ');
}

// Aisle order for the per-day "everything you need" list.
const DAY_CAT_ORDER = [
  'produce', 'meat-seafood', 'dairy', 'bakery', 'deli',
  'pantry', 'canned', 'spices', 'frozen', 'beverages', 'other',
];

// Combine every dish's ingredients for a day (keeps staples — you're cooking).
function aggregateDay(dishes) {
  const merged = new Map();
  for (const dish of dishes) {
    for (const ing of dish.ingredients || []) {
      if (!ing.item) continue;
      const unit = (ing.unit || '').toLowerCase().trim();
      const key = ing.item.toLowerCase().trim() + '|' + unit;
      if (!merged.has(key)) {
        merged.set(key, { item: ing.item, qty: null, unit, category: ing.category || 'other', dishes: [] });
      }
      const line = merged.get(key);
      if (ing.qty != null) line.qty = (line.qty || 0) + Number(ing.qty);
      if (!line.dishes.includes(dish.title)) line.dishes.push(dish.title);
    }
  }
  const byCat = new Map();
  for (const line of merged.values()) {
    if (!byCat.has(line.category)) byCat.set(line.category, []);
    byCat.get(line.category).push(line);
  }
  return [...byCat.keys()]
    .sort((a, b) => {
      const ia = DAY_CAT_ORDER.indexOf(a), ib = DAY_CAT_ORDER.indexOf(b);
      return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib);
    })
    .map(cat => ({ category: cat, items: byCat.get(cat).sort((a, b) => a.item.localeCompare(b.item)) }));
}

function fmtIngQty(line) {
  if (line.qty == null) return '';
  return `${line.qty}${line.unit ? ' ' + line.unit : ''}`;
}

// ---- Menu pages ------------------------------------------------------------

function renderDishDetail(out, dish, recipesByMealId, ratingsByTitle, rel) {
  const recipe = recipesByMealId[dish.id];
  out.push(`### ${dish.title}${isSide(dish) ? ' _(side)_' : ''}\n`);
  if (recipe?.ai?.cliffNotes) out.push(`*${recipe.ai.cliffNotes}*\n`);

  const links = recipeLinks(dish, recipesByMealId, rel);
  if (links) out.push(links + '\n');

  const meta = [];
  if (dish.cuisine) meta.push(`**Cuisine:** ${dish.cuisine}`);
  if (dish.protein && !isSide(dish)) meta.push(`**Protein:** ${dish.protein}`);
  const times = [];
  if (recipe?.prepTime) times.push(`${recipe.prepTime} prep`);
  else if (dish.activeTimeMin) times.push(`${dish.activeTimeMin} min active`);
  if (recipe?.totalTime) times.push(`${recipe.totalTime} total`);
  else if (dish.totalTimeMin) times.push(`${dish.totalTimeMin} min total`);
  if (times.length) meta.push(`**Time:** ${times.join(' · ')}`);
  if (dish.tags?.length) meta.push(`**Tags:** ${dish.tags.join(', ')}`);
  if (meta.length) out.push(meta.join('  \n') + '\n');

  if (dish.notes) out.push(`> ${dish.notes}\n`);

  if (recipe?.ai?.keyTips?.length) {
    out.push('!!! tip "Key Tips"');
    for (const tip of recipe.ai.keyTips) out.push(`    - ${tip}`);
    out.push('');
  }

  const ratings = ratingsFor(ratingsByTitle, dish.title, recipe?.name);
  if (ratings?.length) out.push(ratingSummaryLine(ratings) + '\n');
}

function buildMenuPage(menu, ratingsByTitle, recipesByMealId) {
  const rel = '../';
  const out = [`# Week of ${fmtDate(menu.weekOf)}\n`];

  // Summary table (jumps to each day's section below, plus the cook view)
  out.push('| Day | Date | Dishes | Cuisine | |');
  out.push('|-----|------|--------|---------|---|');
  for (const [day, dishes] of dishesByDay(menu)) {
    const anchor = day.toLowerCase();
    const main = dishes.find(d => !isSide(d)) || dishes[0];
    const names = dishes
      .map(d => (isSide(d) ? `${d.title} _(side)_` : `**${d.title}**`))
      .join('<br>');
    const cook = `[cook →](${rel}days/${menu.weekOf}-${day}.md)`;
    out.push(`| [**${day}**](#${anchor}) | ${fmtDate(dayDate(menu.weekOf, day)).replace(/, \d{4}$/, '')} | ${names} | ${main.cuisine || '—'} | ${cook} |`);
  }
  out.push('');

  // Per-day detail (explicit anchor ids so the table above links here)
  for (const [day, dishes] of dishesByDay(menu)) {
    out.push(`## ${DAY_FULL[day] || day} · ${fmtDate(dayDate(menu.weekOf, day))} {#${day.toLowerCase()}}\n`);
    out.push(`[Day view: all recipes + ingredients →](${rel}days/${menu.weekOf}-${day}.md)\n`);
    for (const dish of dishes) {
      renderDishDetail(out, dish, recipesByMealId, ratingsByTitle, rel);
    }
    out.push('---\n');
  }

  return out.join('\n');
}

// ---- Day pages (the "cook this day" view) ----------------------------------

function buildDayPage(week, day, dishes, recipesByMealId) {
  const rel = '../';
  const out = [`# ${DAY_FULL[day] || day} · ${fmtDate(dayDate(week, day))}\n`];
  out.push(`[← Back to the week](${rel}menus/${week}.md)\n`);

  out.push('## Dishes\n');
  if (dishes.length > 1) {
    out.push(`_Cooking ${dishes.length} things — open each recipe in its own tab._\n`);
  }
  for (const dish of dishes) {
    out.push(`### ${dish.title}${isSide(dish) ? ' · side' : ''}`);
    const recipe = recipesByMealId[dish.id];
    const sub = [];
    if (dish.cuisine) sub.push(dish.cuisine);
    if (recipe?.totalTime) sub.push(recipe.totalTime);
    else if (dish.totalTimeMin) sub.push(`${dish.totalTimeMin} min`);
    if (sub.length) out.push(`*${sub.join(' · ')}*`);
    const links = recipeLinks(dish, recipesByMealId, rel);
    out.push((links ? '\n' + links : '') + '\n');
  }

  out.push('## Everything you need\n');
  const n = dishes.length;
  out.push(`_Combined ingredients for all ${n} dish${n > 1 ? 'es' : ''} on ${DAY_FULL[day] || day}._\n`);
  const multi = n > 1;
  for (const sec of aggregateDay(dishes)) {
    out.push(`### ${titleCase(sec.category)}`);
    for (const it of sec.items) {
      const qty = fmtIngQty(it);
      const who = multi ? ` _(${it.dishes.join(', ')})_` : '';
      out.push(`- [ ] ${it.item}${qty ? ` — ${qty}` : ''}${who}`);
    }
    out.push('');
  }

  return out.join('\n');
}

// ---- Recipe pages ----------------------------------------------------------

function buildRecipePage(stored, meal, ratings) {
  const out = [];
  const title = decodeEntities(stored.name || meal?.title || 'Recipe');
  out.push(`# ${title}\n`);

  if (stored.ai?.cliffNotes) {
    out.push(`*${stored.ai.cliffNotes}*\n`);
  }

  // Your rating front and center, so you know if it's a keeper.
  if (ratings?.length) {
    out.push(ratingSummaryLine(ratings) + '\n');
  }

  // Meta bar
  const meta = [];
  if (stored.url) meta.push(`[Original recipe →](${stored.url})`);
  if (meal?.day && meal?.weekOf) meta.push(`Week of ${fmtDate(meal.weekOf)}, ${meal.day}`);
  if (stored.author) meta.push(`By ${stored.author}`);
  if (meta.length) out.push(meta.join(' · ') + '\n');

  // Times + yield
  const times = [];
  if (stored.prepTime) times.push(`Prep: ${stored.prepTime}`);
  if (stored.cookTime) times.push(`Cook: ${stored.cookTime}`);
  if (stored.totalTime) times.push(`Total: ${stored.totalTime}`);
  if (stored.recipeYield) times.push(`Yield: ${stored.recipeYield}`);
  if (times.length) out.push(times.join(' · ') + '\n');

  // Key tips admonition
  if (stored.ai?.keyTips?.length) {
    out.push('!!! tip "Key Tips"');
    for (const tip of stored.ai.keyTips) {
      out.push(`    - ${tip}`);
    }
    out.push('');
  }

  // Ingredients
  if (stored.recipeIngredient?.length) {
    out.push('## Ingredients\n');
    for (const ing of stored.recipeIngredient) {
      out.push(`- [ ] ${ing}`);
    }
    out.push('');
  }

  // Instructions
  if (stored.recipeInstructions?.length) {
    out.push('## Instructions\n');
    stored.recipeInstructions.forEach((step, i) => {
      out.push(`${i + 1}. ${step}`);
    });
    out.push('');
  }

  // Full reviews & ratings, co-located with the recipe.
  if (ratings?.length) {
    out.push(renderReviews(ratings));
  }

  out.push(`---\n*Fetched ${stored.fetchedAt?.slice(0, 10) || ''}*`);

  return out.join('\n');
}

// ---- History page ----------------------------------------------------------

function buildHistoryPage(history) {
  const out = ['# Ratings & Reviews\n'];

  if (!history.length) {
    out.push('No ratings yet.\n');
    return out.join('\n');
  }

  const sorted = [...history].sort((a, b) => b.date.localeCompare(a.date));

  for (const r of sorted) {
    out.push(`## ${r.title}\n`);
    out.push(`${stars(r.rating)} **${r.rating}/5** · ${fmtDate(r.date)}`);

    const meta = [];
    if (r.cuisine) meta.push(`Cuisine: ${r.cuisine}`);
    if (r.protein) meta.push(`Protein: ${r.protein}`);
    if (r.redo) meta.push('Would cook again ✓');
    if (meta.length) out.push(meta.join(' · '));

    if (r.sourceUrl) out.push(`[Recipe →](${r.sourceUrl})`);
    if (r.notes) out.push(`\n> ${r.notes}`);
    out.push('\n---\n');
  }

  return out.join('\n');
}

// ---- Index page (dashboard) ------------------------------------------------

// One dashboard section for a given week. This week and next week use this
// same builder, so they are always formatted identically.
function buildWeekSection(label, week, menu, shoppingWeeks) {
  const out = [`## ${label} · ${fmtDate(week)}\n`];
  if (!menu || !menu.meals.length) {
    out.push('_Nothing planned yet — ask Claude to build this week\'s menu._\n');
    out.push('[Browse menus →](menus/index.md)\n');
    return out.join('\n');
  }
  out.push('| Day | Dishes | |');
  out.push('|-----|--------|---|');
  for (const [day, dishes] of dishesByDay(menu)) {
    const names = dishes
      .map(d => (isSide(d) ? `${d.title} _(side)_` : `**${d.title}**`))
      .join('<br>');
    out.push(`| **${day}** | ${names} | [cook →](days/${week}-${day}.md) |`);
  }
  out.push('');
  const links = [`[Full menu →](menus/${week}.md)`];
  if (shoppingWeeks.includes(week)) {
    links.push(`[Shopping list →](shopping/${week}.md)`);
  }
  out.push(links.join(' · ') + '\n');
  return out.join('\n');
}

function buildIndexPage(ctx) {
  const { thisWeek, nextWeek, thisWeekMenu, nextWeekMenu, shoppingWeeks } = ctx;
  const out = ['# cookwhat\n'];
  out.push('Your weekly meal plans, shopping lists, and recipes — all in one place.\n');
  out.push(buildWeekSection('This week', thisWeek, thisWeekMenu, shoppingWeeks));
  out.push(buildWeekSection('Next week', nextWeek, nextWeekMenu, shoppingWeeks));
  out.push('---\n');
  out.push('**Browse:** ' + [
    '[All menus](menus/index.md)',
    '[Shopping lists](shopping/index.md)',
    '[Recipes](recipes/index.md)',
    '[Ratings](history.md)',
  ].join(' · ') + '\n');
  return out.join('\n');
}

// ---- Section landing pages -------------------------------------------------

function buildMenusIndex(menus, shoppingWeeks) {
  const out = ['# Menus\n'];
  if (!menus.length) { out.push('No menus yet.\n'); return out.join('\n'); }
  out.push('| Week | Meals | Shopping |');
  out.push('|------|-------|----------|');
  for (const m of menus) {
    const shop = shoppingWeeks.includes(m.weekOf)
      ? `[list →](../shopping/${m.weekOf}.md)`
      : '—';
    out.push(`| [${fmtDate(m.weekOf)}](${m.weekOf}.md) | ${m.meals.length} | ${shop} |`);
  }
  out.push('');
  return out.join('\n');
}

function buildShoppingIndex(shoppingWeeks) {
  const out = ['# Shopping Lists\n'];
  if (!shoppingWeeks.length) { out.push('No shopping lists yet.\n'); return out.join('\n'); }
  for (const w of shoppingWeeks) {
    out.push(`- [Week of ${fmtDate(w)}](${w}.md)`);
  }
  out.push('');
  return out.join('\n');
}

function buildRecipesIndex(recipesByMealId, mealLookup, ratingsByTitle) {
  const out = ['# Recipes\n'];
  const rows = Object.entries(recipesByMealId).map(([mealId, stored]) => {
    const meal = mealLookup[mealId] || {};
    const name = decodeEntities(stored.name || meal.title || 'Recipe');
    const ratings = ratingsFor(ratingsByTitle, meal.title, stored.name);
    const avg = ratings ? avgRating(ratings) : null;
    let host = '';
    try { host = stored.url ? new URL(stored.url).hostname.replace(/^www\./, '') : ''; } catch {}
    return {
      name,
      mealId,
      cuisine: meal.cuisine || '—',
      protein: meal.protein || '—',
      rating: avg != null ? `${stars(Math.round(avg))} ${avg.toFixed(1)}` : '—',
      source: stored.url ? `[${host}](${stored.url})` : '—',
    };
  }).sort((a, b) => a.name.localeCompare(b.name));

  if (!rows.length) { out.push('No recipes captured yet.\n'); return out.join('\n'); }

  out.push('| Recipe | Cuisine | Protein | My Rating | Source |');
  out.push('|--------|---------|---------|-----------|--------|');
  for (const r of rows) {
    out.push(`| [${r.name}](${r.mealId}.md) | ${r.cuisine} | ${r.protein} | ${r.rating} | ${r.source} |`);
  }
  out.push('');
  return out.join('\n');
}

// ---- mkdocs.yml ------------------------------------------------------------

function buildMkdocsYml(menus, navWeeks) {
  // navWeeks: [{ label: 'This Week', week: '2026-06-14' }, ...] — quick-access
  // tabs that jump straight to a week's menu. Browse sections are single
  // landing pages so the bar stays tidy as weeks accumulate.
  const navWeekSet = new Set(navWeeks.map(n => n.week));
  const weekTabs = navWeeks
    .map(n => `  - ${n.label}: menus/${n.week}.md`)
    .join('\n');

  // Detail pages are reached via links, not listed in nav. Menu weeks that are
  // promoted to a quick-access tab must NOT also be listed here (mkdocs --strict
  // errors on overlap), so list only the remaining menu weeks explicitly.
  const notInNav = [
    ...menus.filter(m => !navWeekSet.has(m.weekOf)).map(m => `  menus/${m.weekOf}.md`),
    '  days/*.md',
    '  shopping/2*.md',
    '  recipes/*-*.md',
  ].join('\n');

  return `site_name: cookwhat
site_description: AI-augmented weekly menu plans and shopping lists
theme:
  name: material
  font:
    text: Inter
    heading: Lora
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

not_in_nav: |
${notInNav}

nav:
  - Home: index.md
${weekTabs ? weekTabs + '\n' : ''}  - Menus: menus/index.md
  - Shopping: shopping/index.md
  - Recipes: recipes/index.md
  - Ratings: history.md
  - Help:
    - How to Use: HOW_TO_USE.md
    - Config: CONFIG.md
`;
}

// ---- main ------------------------------------------------------------------

function main() {
  // Load ratings
  const histPath = join(DATA, 'history.json');
  const history = existsSync(histPath) ? readJson(histPath) : [];
  const ratingsByTitle = {};
  for (const r of history) {
    const k = (r.title || '').toLowerCase().trim();
    (ratingsByTitle[k] ??= []).push(r);
  }

  // Load stored recipes indexed by mealId
  const recipesDir = join(DATA, 'recipes');
  const recipesByMealId = {};
  if (existsSync(recipesDir)) {
    for (const f of readdirSync(recipesDir).filter(f => f.endsWith('.json'))) {
      const r = readJson(join(recipesDir, f));
      if (r.mealId) recipesByMealId[r.mealId] = r;
    }
  }

  // Menus sorted latest-first
  const menuFiles = readdirSync(join(DATA, 'menus'))
    .filter(f => f.endsWith('.json'))
    .sort()
    .reverse();
  const menus = menuFiles.map(f => readJson(join(DATA, 'menus', f)));

  // Shopping lists
  const shopFiles = readdirSync(join(DATA, 'shopping'))
    .filter(f => f.endsWith('.md'))
    .sort()
    .reverse();
  const shoppingWeeks = shopFiles.map(f => f.replace('.md', ''));

  // Build a lookup of mealId → { meal, weekOf } for recipe pages
  const mealLookup = {};
  const menusByWeek = {};
  for (const menu of menus) {
    menusByWeek[menu.weekOf] = menu;
    for (const meal of menu.meals) {
      mealLookup[meal.id] = { ...meal, weekOf: menu.weekOf };
    }
  }

  // This week / next week, relative to build time (weeks start Sunday).
  // COOKWHAT_TODAY=YYYY-MM-DD overrides "today" for previewing other weeks.
  const today = process.env.COOKWHAT_TODAY
    ? new Date(process.env.COOKWHAT_TODAY + 'T00:00:00')
    : new Date();
  const thisWeek = sundayOf(today);
  const nextWeek = addDays(thisWeek, 7);
  const thisWeekMenu = menusByWeek[thisWeek];
  const nextWeekMenu = menusByWeek[nextWeek];

  // Quick-access tabs only for weeks that actually have a menu (avoids
  // linking to a page that doesn't exist, which --strict would reject).
  const navWeeks = [];
  if (thisWeekMenu) navWeeks.push({ label: 'This Week', week: thisWeek });
  if (nextWeekMenu) navWeeks.push({ label: 'Next Week', week: nextWeek });

  ensureDir(join(DOCS, 'menus'));
  ensureDir(join(DOCS, 'days'));
  ensureDir(join(DOCS, 'shopping'));
  ensureDir(join(DOCS, 'recipes'));

  // Warm palette stylesheet (referenced by extra_css)
  write(join(DOCS, 'stylesheets', 'extra.css'), EXTRA_CSS);

  // Menu pages + per-day "cook this day" pages
  let dayCount = 0;
  for (const menu of menus) {
    write(
      join(DOCS, 'menus', `${menu.weekOf}.md`),
      buildMenuPage(menu, ratingsByTitle, recipesByMealId)
    );
    for (const [day, dishes] of dishesByDay(menu)) {
      write(
        join(DOCS, 'days', `${menu.weekOf}-${day}.md`),
        buildDayPage(menu.weekOf, day, dishes, recipesByMealId)
      );
      dayCount++;
    }
  }

  // Shopping lists
  for (const f of shopFiles) {
    const content = readFileSync(join(DATA, 'shopping', f), 'utf8');
    write(join(DOCS, 'shopping', f), content);
  }

  // Recipe pages
  let recipeCount = 0;
  for (const [mealId, stored] of Object.entries(recipesByMealId)) {
    const meal = mealLookup[mealId];
    const ratings = ratingsFor(ratingsByTitle, meal?.title, stored.name);
    write(join(DOCS, 'recipes', `${mealId}.md`), buildRecipePage(stored, meal, ratings));
    recipeCount++;
  }

  // Section landing pages
  write(join(DOCS, 'menus', 'index.md'), buildMenusIndex(menus, shoppingWeeks));
  write(join(DOCS, 'shopping', 'index.md'), buildShoppingIndex(shoppingWeeks));
  write(join(DOCS, 'recipes', 'index.md'), buildRecipesIndex(recipesByMealId, mealLookup, ratingsByTitle));

  // History
  write(join(DOCS, 'history.md'), buildHistoryPage(history));

  // Index (dashboard)
  write(join(DOCS, 'index.md'), buildIndexPage({
    thisWeek, nextWeek, thisWeekMenu, nextWeekMenu, shoppingWeeks, recipesByMealId,
  }));

  // mkdocs.yml
  write(join(ROOT, 'mkdocs.yml'), buildMkdocsYml(menus, navWeeks));

  console.log(
    `Docs built: ${menus.length} menu(s), ${dayCount} day page(s), ` +
    `${shoppingWeeks.length} shopping list(s), ${recipeCount} recipe(s), ` +
    `${history.length} rating(s)`
  );
}

main();
